project:
  type: website
  output-dir: docs

website:
  title: "LASER"
  navbar:
    logo: img/laser.png
    search: true
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - href: conferences.qmd
        text: Conferences & Workshops
      - past.qmd
    right:
      - about.qmd


format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

