project:
  type: website
  output-dir: docs

website:
  title: "LASER"
  navbar:
    logo: img/laser.png
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - past.qmd


format:
  html:
    theme: superhero
    css: styles.css
    toc: true

editor: visual

